DOCKER_REPOSITORY ?= altschool/docker-gc
DOCKER_TAG ?= docker_v$(shell cat version.txt)_base

DOCKER ?= docker
export DOCKER

.PHONY: all image push

image:
	$(DOCKER) build -t $(DOCKER_REPOSITORY):$(DOCKER_TAG) .

push: image
	$(DOCKER) push $(DOCKER_REPOSITORY):$(DOCKER_TAG)
